### ISSUE TITLE
Codecov errors

### ISSUE THREAD

**Issue by K-Meech** [brainglobe/brainglobe-utils#41]
Codecov appears to be failing to run correctly on this repo - e.g. [in this run](https://github.com/brainglobe/brainglobe-utils/actions/runs/8065986996) it warns of ```Codecov: Failed to properly create commit: The process '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1```

This seems to be the case for all runs over the past month or so. Potentially related to [using v4 of the codecov action](https://github.com/codecov/codecov-action/issues/1274)

**Comment by adamltyson** [comment]
This should be solved with https://github.com/neuroinformatics-unit/actions/pull/46 (and adding the token).

**Comment by K-Meech** [comment]
@adamltyson Now that https://github.com/neuroinformatics-unit/actions/pull/46 has been merged, would it be possible to add the token to get codecov working on this repo again?

**Comment by adamltyson** [comment]
It's been added as an organisation token (`CODECOV_TOKEN`). It seems to be working in the @neuroinformatics-unit, so it should work for @brainglobe :crossed_fingers:

**Comment by K-Meech** [comment]
Great - thanks @adamltyson !

**Comment by K-Meech** [comment]
Codecov is running correctly now, so I'll close this issue.
