### ISSUE TITLE
Writing 3D tiffs throws deprecation warning

### ISSUE THREAD

**Issue by K-Meech** [brainglobe/brainglobe-utils#45]
Writing a 3D tiff via the `image_io` sub-module throws a `DeprecationWarning` e.g.:
```
image = np.ones((4, 4, 4))
file_path = Path(tmp_dir) / "test_array.tif"
save.to_tiff(image, file_path)
```
```
DeprecationWarning: <tifffile.TiffWriter.write> data with shape (4, 4, 4) and dtype 'float64' are stored as RGB with contiguous samples. Future versions will store such data as MINISBLACK in separate pages by default, unless the 'photometric' parameter is specified.
```
Should the `photometric` / `planarconfig` be set explicitly to keep the old settings? Or are you happy to use the new `tifffile` defaults and just add this warning to the list of those ignored by pytest?

**Comment by adamltyson** [comment]
It would be good to know what's going on here, so we can explicitly set the parameter. We rarely (if ever) need to write either float64 or RGB though, so it would be good to know what this should be set to for our "normal" usage (typically 16bit greyscale, 2/3D).

**Comment by K-Meech** [comment]
The same error occurs with `int32` data, so it's more to do with the image's shape. It appears to be recognising any image with a length of [3 or 4 in the last axis as rgb](https://github.com/cgohlke/tifffile/blob/master/tifffile/tifffile.py#L2583). [In their examples](https://github.com/cgohlke/tifffile?tab=readme-ov-file#examples) they recommend using `photometric='minisblack'` for grayscale images. The explanation of the different `photometric` options is [linked here](https://github.com/cgohlke/tifffile/blob/master/tifffile/tifffile.py#L1877)

**Comment by adamltyson** [comment]
In that case I would definitely set it to `MINISBLACK` (ideally as a  default parameter in the BrainGlobe function rather than hardcoding) unless @alessandrofelder thinks differently?

**Comment by K-Meech** [comment]
Ok - will do! I'll make a PR to add this
