### ISSUE TITLE
Create tests for brainmapper sub-module

### ISSUE THREAD

**Issue by K-Meech** [brainglobe/brainglobe-utils#49]
More tests need to be added for the `brainmapper` sub-module - aiming at >90% coverage.

**Comment by K-Meech** [comment]
I'm looking into writing tests for the [`summarise_points_by_atlas_region` function](https://github.com/brainglobe/brainglobe-utils/blob/main/brainglobe_utils/brainmapper/analysis.py#L226). This requires a corresponding `BrainGlobeAtlas` object, but I'm not sure which one corresponds to the [test `volume.csv` file](https://github.com/brainglobe/brainglobe-utils/blob/main/tests/data/brainmapper/volumes.csv). 

Any ideas? @alessandrofelder

**Comment by alessandrofelder** [comment]
My guess is that's it's an Allen one (I know it's definitely a mouse thanks to @niksirbi ) - I would try using `BrainGlobeAtlas("allen_mouse_100um")` in the tests (because it's the lowest res one) and see how far you get?

@adamltyson may know more exactly how this data was generated?

**Comment by adamltyson** [comment]
I assume it's `allen_mouse_something`. No idea which, but to some level of precision, it shouldn't matter. The volumes are in mm^3 and that's the same across all resolutions.
