### ISSUE TITLE
Add a save_any function to image_io

### ISSUE THREAD

**Issue by K-Meech** [brainglobe/brainglobe-utils#50]
Image_io has a [`load_any` function](https://github.com/brainglobe/brainglobe-utils/blob/main/brainglobe_utils/image_io/load.py#L26) that recognises the image file extension and calls the appropriate loading function. It would be useful to add a corresponding `save_any` function, [similar to here](https://github.com/brainglobe/brainglobe-utils/pull/48#discussion_r1523065323)

**Comment by K-Meech** [comment]
We should also support saving a txt file with a tiff sequence as part of this. We already support loading such files via [`load_any`](https://github.com/brainglobe/brainglobe-utils/blob/main/brainglobe_utils/image_io/load.py#L26) and [`load_img_sequence`](https://github.com/brainglobe/brainglobe-utils/blob/main/brainglobe_utils/image_io/load.py#L325)

**Comment by adamltyson** [comment]
> We should also support saving a txt file with a tiff sequence as part of this.

I don't think we have any need for this TBH. The `image_io` module is now just to support BrainGlobe tools, and none need to write to this format.

**Comment by alessandrofelder** [comment]
Do you think BrainGlobe tools will need to read this format?

**Comment by adamltyson** [comment]
It was included for historical reasons to support `brainreg` & `brainmapper`. I think it's worth keeping as long as it isn't too much overhead.
